# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strawhat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("strawhat.proto", :syntax => :proto3) do
    add_message "strawhat.Strawhat" do
      optional :serviceID, :string, 1
      optional :protocol, :enum, 2, "strawhat.Protocol"
    end
    add_enum "strawhat.Protocol" do
      value :Tcp, 0
      value :Udp, 1
    end
  end
end

module Strawhat
  Strawhat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("strawhat.Strawhat").msgclass
  Protocol = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("strawhat.Protocol").enummodule
end
