# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strawhat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("strawhat.proto", :syntax => :proto3) do
    add_message "strawhat.Strawhat" do
      optional :serviceID, :string, 1
      optional :transport, :enum, 2, "strawhat.Transport"
    end
    add_enum "strawhat.Transport" do
      value :Empty, 0
      value :Tcp, 1
      value :Udp, 3
    end
  end
end

module Strawhat
  Strawhat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("strawhat.Strawhat").msgclass
  Transport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("strawhat.Transport").enummodule
end
