<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strawhat.proto

namespace Strawhat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>strawhat.Foliv</code>
 */
class Foliv extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string serviceID = 1;</code>
     */
    protected $serviceID = '';
    /**
     * Generated from protobuf field <code>.strawhat.Protocol protocol = 2;</code>
     */
    protected $protocol = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $serviceID
     *     @type int $protocol
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Strawhat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string serviceID = 1;</code>
     * @return string
     */
    public function getServiceID()
    {
        return $this->serviceID;
    }

    /**
     * Generated from protobuf field <code>string serviceID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceID($var)
    {
        GPBUtil::checkString($var, True);
        $this->serviceID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.strawhat.Protocol protocol = 2;</code>
     * @return int
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * Generated from protobuf field <code>.strawhat.Protocol protocol = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setProtocol($var)
    {
        GPBUtil::checkEnum($var, \Strawhat\Protocol::class);
        $this->protocol = $var;

        return $this;
    }

}

