<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strawhat.proto

namespace Strawhat;

use UnexpectedValueException;

/**
 * Protobuf type <code>strawhat.Transport</code>
 */
class Transport
{
    /**
     * Generated from protobuf enum <code>Empty = 0;</code>
     */
    const PBEmpty = 0;
    /**
     * Generated from protobuf enum <code>Tcp = 1;</code>
     */
    const Tcp = 1;
    /**
     * Generated from protobuf enum <code>Udp = 3;</code>
     */
    const Udp = 3;

    private static $valueToName = [
        self::PBEmpty => 'PBEmpty',
        self::Tcp => 'Tcp',
        self::Udp => 'Udp',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

