// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: strawhat.proto

package strawhat;

public final class StrawhatOuterClass {
  private StrawhatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code strawhat.Protocol}
   */
  public enum Protocol
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Empty = 0;</code>
     */
    Empty(0),
    /**
     * <code>Tcp = 1;</code>
     */
    Tcp(1),
    /**
     * <code>Udp = 3;</code>
     */
    Udp(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Empty = 0;</code>
     */
    public static final int Empty_VALUE = 0;
    /**
     * <code>Tcp = 1;</code>
     */
    public static final int Tcp_VALUE = 1;
    /**
     * <code>Udp = 3;</code>
     */
    public static final int Udp_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Protocol valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Protocol forNumber(int value) {
      switch (value) {
        case 0: return Empty;
        case 1: return Tcp;
        case 3: return Udp;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Protocol>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Protocol> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Protocol>() {
            public Protocol findValueByNumber(int number) {
              return Protocol.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return strawhat.StrawhatOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Protocol[] VALUES = values();

    public static Protocol valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Protocol(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:strawhat.Protocol)
  }

  public interface StrawhatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:strawhat.Strawhat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string serviceID = 1;</code>
     * @return The serviceID.
     */
    java.lang.String getServiceID();
    /**
     * <code>string serviceID = 1;</code>
     * @return The bytes for serviceID.
     */
    com.google.protobuf.ByteString
        getServiceIDBytes();

    /**
     * <code>.strawhat.Protocol protocol = 2;</code>
     * @return The enum numeric value on the wire for protocol.
     */
    int getProtocolValue();
    /**
     * <code>.strawhat.Protocol protocol = 2;</code>
     * @return The protocol.
     */
    strawhat.StrawhatOuterClass.Protocol getProtocol();
  }
  /**
   * Protobuf type {@code strawhat.Strawhat}
   */
  public static final class Strawhat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:strawhat.Strawhat)
      StrawhatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Strawhat.newBuilder() to construct.
    private Strawhat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Strawhat() {
      serviceID_ = "";
      protocol_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Strawhat();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Strawhat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serviceID_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              protocol_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return strawhat.StrawhatOuterClass.internal_static_strawhat_Strawhat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return strawhat.StrawhatOuterClass.internal_static_strawhat_Strawhat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              strawhat.StrawhatOuterClass.Strawhat.class, strawhat.StrawhatOuterClass.Strawhat.Builder.class);
    }

    public static final int SERVICEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object serviceID_;
    /**
     * <code>string serviceID = 1;</code>
     * @return The serviceID.
     */
    @java.lang.Override
    public java.lang.String getServiceID() {
      java.lang.Object ref = serviceID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceID_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceID = 1;</code>
     * @return The bytes for serviceID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceIDBytes() {
      java.lang.Object ref = serviceID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTOCOL_FIELD_NUMBER = 2;
    private int protocol_;
    /**
     * <code>.strawhat.Protocol protocol = 2;</code>
     * @return The enum numeric value on the wire for protocol.
     */
    @java.lang.Override public int getProtocolValue() {
      return protocol_;
    }
    /**
     * <code>.strawhat.Protocol protocol = 2;</code>
     * @return The protocol.
     */
    @java.lang.Override public strawhat.StrawhatOuterClass.Protocol getProtocol() {
      @SuppressWarnings("deprecation")
      strawhat.StrawhatOuterClass.Protocol result = strawhat.StrawhatOuterClass.Protocol.valueOf(protocol_);
      return result == null ? strawhat.StrawhatOuterClass.Protocol.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServiceIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceID_);
      }
      if (protocol_ != strawhat.StrawhatOuterClass.Protocol.Empty.getNumber()) {
        output.writeEnum(2, protocol_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServiceIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceID_);
      }
      if (protocol_ != strawhat.StrawhatOuterClass.Protocol.Empty.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, protocol_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof strawhat.StrawhatOuterClass.Strawhat)) {
        return super.equals(obj);
      }
      strawhat.StrawhatOuterClass.Strawhat other = (strawhat.StrawhatOuterClass.Strawhat) obj;

      if (!getServiceID()
          .equals(other.getServiceID())) return false;
      if (protocol_ != other.protocol_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getServiceID().hashCode();
      hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + protocol_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static strawhat.StrawhatOuterClass.Strawhat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static strawhat.StrawhatOuterClass.Strawhat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(strawhat.StrawhatOuterClass.Strawhat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code strawhat.Strawhat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:strawhat.Strawhat)
        strawhat.StrawhatOuterClass.StrawhatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return strawhat.StrawhatOuterClass.internal_static_strawhat_Strawhat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return strawhat.StrawhatOuterClass.internal_static_strawhat_Strawhat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                strawhat.StrawhatOuterClass.Strawhat.class, strawhat.StrawhatOuterClass.Strawhat.Builder.class);
      }

      // Construct using strawhat.StrawhatOuterClass.Strawhat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serviceID_ = "";

        protocol_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return strawhat.StrawhatOuterClass.internal_static_strawhat_Strawhat_descriptor;
      }

      @java.lang.Override
      public strawhat.StrawhatOuterClass.Strawhat getDefaultInstanceForType() {
        return strawhat.StrawhatOuterClass.Strawhat.getDefaultInstance();
      }

      @java.lang.Override
      public strawhat.StrawhatOuterClass.Strawhat build() {
        strawhat.StrawhatOuterClass.Strawhat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public strawhat.StrawhatOuterClass.Strawhat buildPartial() {
        strawhat.StrawhatOuterClass.Strawhat result = new strawhat.StrawhatOuterClass.Strawhat(this);
        result.serviceID_ = serviceID_;
        result.protocol_ = protocol_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof strawhat.StrawhatOuterClass.Strawhat) {
          return mergeFrom((strawhat.StrawhatOuterClass.Strawhat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(strawhat.StrawhatOuterClass.Strawhat other) {
        if (other == strawhat.StrawhatOuterClass.Strawhat.getDefaultInstance()) return this;
        if (!other.getServiceID().isEmpty()) {
          serviceID_ = other.serviceID_;
          onChanged();
        }
        if (other.protocol_ != 0) {
          setProtocolValue(other.getProtocolValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        strawhat.StrawhatOuterClass.Strawhat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (strawhat.StrawhatOuterClass.Strawhat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object serviceID_ = "";
      /**
       * <code>string serviceID = 1;</code>
       * @return The serviceID.
       */
      public java.lang.String getServiceID() {
        java.lang.Object ref = serviceID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serviceID = 1;</code>
       * @return The bytes for serviceID.
       */
      public com.google.protobuf.ByteString
          getServiceIDBytes() {
        java.lang.Object ref = serviceID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceID = 1;</code>
       * @param value The serviceID to set.
       * @return This builder for chaining.
       */
      public Builder setServiceID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceID() {
        
        serviceID_ = getDefaultInstance().getServiceID();
        onChanged();
        return this;
      }
      /**
       * <code>string serviceID = 1;</code>
       * @param value The bytes for serviceID to set.
       * @return This builder for chaining.
       */
      public Builder setServiceIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceID_ = value;
        onChanged();
        return this;
      }

      private int protocol_ = 0;
      /**
       * <code>.strawhat.Protocol protocol = 2;</code>
       * @return The enum numeric value on the wire for protocol.
       */
      @java.lang.Override public int getProtocolValue() {
        return protocol_;
      }
      /**
       * <code>.strawhat.Protocol protocol = 2;</code>
       * @param value The enum numeric value on the wire for protocol to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolValue(int value) {
        
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.strawhat.Protocol protocol = 2;</code>
       * @return The protocol.
       */
      @java.lang.Override
      public strawhat.StrawhatOuterClass.Protocol getProtocol() {
        @SuppressWarnings("deprecation")
        strawhat.StrawhatOuterClass.Protocol result = strawhat.StrawhatOuterClass.Protocol.valueOf(protocol_);
        return result == null ? strawhat.StrawhatOuterClass.Protocol.UNRECOGNIZED : result;
      }
      /**
       * <code>.strawhat.Protocol protocol = 2;</code>
       * @param value The protocol to set.
       * @return This builder for chaining.
       */
      public Builder setProtocol(strawhat.StrawhatOuterClass.Protocol value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        protocol_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.strawhat.Protocol protocol = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocol() {
        
        protocol_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:strawhat.Strawhat)
    }

    // @@protoc_insertion_point(class_scope:strawhat.Strawhat)
    private static final strawhat.StrawhatOuterClass.Strawhat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new strawhat.StrawhatOuterClass.Strawhat();
    }

    public static strawhat.StrawhatOuterClass.Strawhat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Strawhat>
        PARSER = new com.google.protobuf.AbstractParser<Strawhat>() {
      @java.lang.Override
      public Strawhat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Strawhat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Strawhat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Strawhat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public strawhat.StrawhatOuterClass.Strawhat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strawhat_Strawhat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strawhat_Strawhat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016strawhat.proto\022\010strawhat\"C\n\010Strawhat\022\021" +
      "\n\tserviceID\030\001 \001(\t\022$\n\010protocol\030\002 \001(\0162\022.st" +
      "rawhat.Protocol*\'\n\010Protocol\022\t\n\005Empty\020\000\022\007" +
      "\n\003Tcp\020\001\022\007\n\003Udp\020\003B\014Z\n./strawhatb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_strawhat_Strawhat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_strawhat_Strawhat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strawhat_Strawhat_descriptor,
        new java.lang.String[] { "ServiceID", "Protocol", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
